name: 'Submodule Branch Check'
author: 'jtmullen'
description: 'Check that the commit of a submodule is on a specific branch descended from the previous one'
branding:
  icon: 'corner-down-right'
  color: 'orange'
inputs:
  path:
    descripton: "The path to the submodule"
    required: true
  branch:
    description: "Which branch the submodule must be on"
    required: false
    default: ''
  first_parent:
    description: "Require submodule commit to be an ancestor of specified branch strictly along first-parent path"
    required: false
    default: ''
  pass_if_unchanged:
    description: "If the check should always pass if the submodule hasn't been changed on a branch/commit"
    required: false
    default: ''
  fetch_depth:
    description: "The fetch depth for both involved branches if run on a PR"
    required: false
    default: ''
  sub_fetch_depth:
    description: "The fetch depth for the submodule"
    required: false
    default: ''  
  require_head:
    description: "If the submodule should be required to be on the head commit of the specified branch"
    required: false
    default: ''
  event_path:
    description: "Override the path to the github event json file. Used for testing."
    required: false
    default: ''
  
outputs:
  fails:
    description: "Cause of failure, if run failed"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
