name: 'Submodule Branch Check'
author: 'jtmullen'
description: 'Check that the commit of a submodule is on a specific branch descended from the previous one'
branding:
  icon: 'corner-down-right'
  color: 'orange'
inputs:
  path:
    descripton: "The path to the submodule"
    required: true
  branch:
    description: "Which branch the submodule must be on"
    required: false
    default: ''
  token:
    description: "Token for accessing the Submodule"
    required: false
    default: ''
outputs:
  fails:
    description: "Cause of failure, if run failed"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
